# NOTION_DB_IDS="32ee4d67321745fa8af54885b1bc28d6,f3877a9dfce74e0792454cc6a20be80e"
# NOTION_DUE_PROP="Date"   # default; we override per-DB below
# Map each database to: date property, extra fields to show, and optional friendly name
databases:
  "32ee4d67321745fa8af54885b1bc28d6":   # Applications
    name: Applications
    date_property: Deadline
    fields: [Type, Company]               # you asked for these
  "f3877a9dfce74e0792454cc6a20be80e":   # Coursework/Homework
    name: Assignments
    date_property: Date
    fields: [Class, Type]